# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import matrix_pb2 as matrix__pb2


class MatrixCalcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BlockAdd = channel.unary_unary(
                '/MatrixCalc/BlockAdd',
                request_serializer=matrix__pb2.Request.SerializeToString,
                response_deserializer=matrix__pb2.Reply.FromString,
                )
        self.BlockMult = channel.unary_unary(
                '/MatrixCalc/BlockMult',
                request_serializer=matrix__pb2.Request.SerializeToString,
                response_deserializer=matrix__pb2.Reply.FromString,
                )


class MatrixCalcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BlockAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockMult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixCalcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BlockAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockAdd,
                    request_deserializer=matrix__pb2.Request.FromString,
                    response_serializer=matrix__pb2.Reply.SerializeToString,
            ),
            'BlockMult': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockMult,
                    request_deserializer=matrix__pb2.Request.FromString,
                    response_serializer=matrix__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MatrixCalc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatrixCalc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BlockAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MatrixCalc/BlockAdd',
            matrix__pb2.Request.SerializeToString,
            matrix__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockMult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MatrixCalc/BlockMult',
            matrix__pb2.Request.SerializeToString,
            matrix__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
